export type Lang = "de" | "en" | "tr" | "ar"

export type Localized = Record<Lang, string>

export interface MenuItem {
  id: string
  num: string
  name: Localized
  desc: Localized
  price: number
}

export const REST = {
  name: "Antalya Döner & Kebab",
  phone: "+49 155 637 172 18",
  phoneHref: "tel:+4915563717218",
  email: "antalyadoener6@gmail.com",
  address: "Am Florapark 125, 39128 Magdeburg",
  maps: "https://www.google.com/maps/search/?api=1&query=Antalya+D%C3%B6ner+%26+Kebab+Am+Florapark+125+39128+Magdeburg",
}

export const TR = {
  de: {
    nav: { menu: "Speisekarte", about: "Über uns", contact: "Kontakt", callOrder: "Anrufen & Bestellen" },
    hero: {
      subline: "Magdeburgs heißester Döner — frisch geschnitten am Florapark.",
      preorder: "Jetzt vorbestellen",
      toMenu: "Zur Speisekarte",
      hours: "Mo–Sa: 10:00–20:00 Uhr",
    },
    banner: { line1: "Bestellungen NUR telefonisch — kein WhatsApp!", line2: "Ruf an, bestell vor, zahl bei Abholung" },
    menu: { title: "Speisekarte", subtitle: "Frisch zubereitet, direkt am Florapark", add: "Hinzufügen" },
    categories: {
      doner: "Dönergerichte",
      pizza: "Türkische Pizza",
      durum: "Dürüm",
      teller: "Teller & Boxen",
      fastfood: "Fast Food",
      salate: "Salate",
      menus: "Menüs",
      getranke: "Getränke",
    },
    cart: {
      title: "Deine Bestellung",
      empty: "Noch nichts ausgewählt.",
      emptyHint: "Tipp auf ein Gericht, um es hinzuzufügen.",
      total: "Gesamt",
      payNote: "Zahlung bei Abholung — nur Barzahlung",
      checkout: "Telefonisch bestellen",
      callInstruction: "Ruf an und nenn uns deine Bestellung!",
      callButton: "Jetzt anrufen",
      noWhatsapp: "Kein WhatsApp — nur Telefonanrufe!",
      noteLabel: "Anmerkungen",
      notePlaceholder: "Z. B. extra scharf, ohne Zwiebeln, Allergie …",
    },
    about: {
      title: "Authentisch. Frisch. Legendär.",
      p1: "Mitten in Magdeburg, am Florapark, servieren wir seit Jahren echten türkischen Döner — frisch geschnitten, mit knusprigem Fladenbrot und hausgemachten Soßen.",
      p2: "Bei uns zählt nur die beste Qualität: frisches Gemüse, würziges Fleisch vom Spieß und traditionelle Rezepte. Komm vorbei und schmeck den Unterschied.",
      badge1: "Frische Zutaten",
      badge2: "Traditionelle Rezepte",
      badge3: "Vom Spieß geschnitten",
    },
    contact: {
      title: "Kontakt & Öffnungszeiten",
      addressLabel: "Adresse",
      addressExtra: "Bei Spargelhalle & Getränkequelle",
      phoneLabel: "Telefon",
      noWhatsapp: "Kein WhatsApp — nur Anrufe!",
      emailLabel: "E-Mail",
      hoursLabel: "Öffnungszeiten",
      monSat: "Montag–Samstag",
      monSatTime: "10:00–20:00 Uhr",
      sun: "Sonntag",
      sunClosed: "Geschlossen",
      mapLabel: "So findest du uns",
      directions: "Route planen",
    },
    footer: {
      hours: "Öffnungszeiten",
      rights: "Alle Rechte vorbehalten.",
      legal: "Rechtliches",
      imprint: "Impressum",
      privacy: "Datenschutz",
      cookies: "Cookie-Einstellungen",
    },
    cookie: {
      title: "Wir respektieren deine Privatsphäre",
      text: "Wir verwenden nur technisch notwendige Cookies (Sprachauswahl & Bestellung). Optionale Cookies für die Google-Maps-Karte werden erst nach deiner Zustimmung geladen.",
      acceptAll: "Alle akzeptieren",
      necessaryOnly: "Nur notwendige",
    },
  },
  en: {
    nav: { menu: "Menu", about: "About", contact: "Contact", callOrder: "Call & Order" },
    hero: {
      subline: "Magdeburg's hottest döner — freshly sliced at Florapark.",
      preorder: "Pre-order now",
      toMenu: "View Menu",
      hours: "Mon–Sat: 10:00 AM–8:00 PM",
    },
    banner: { line1: "Orders by PHONE only — no WhatsApp!", line2: "Call, pre-order, pay on pickup" },
    menu: { title: "Menu", subtitle: "Freshly prepared, right at Florapark", add: "Add" },
    categories: {
      doner: "Döner Dishes",
      pizza: "Turkish Pizza",
      durum: "Dürüm Wraps",
      teller: "Plates & Boxes",
      fastfood: "Fast Food",
      salate: "Salads",
      menus: "Combo Meals",
      getranke: "Drinks",
    },
    cart: {
      title: "Your Order",
      empty: "Nothing selected yet.",
      emptyHint: "Tap a dish to add it.",
      total: "Total",
      payNote: "Payment on pickup — cash only",
      checkout: "Order by phone",
      callInstruction: "Call us and tell us your order!",
      callButton: "Call now",
      noWhatsapp: "No WhatsApp — phone calls only!",
      noteLabel: "Special requests",
      notePlaceholder: "E.g. extra spicy, no onions, allergy …",
    },
    about: {
      title: "Authentic. Fresh. Legendary.",
      p1: "In the heart of Magdeburg, at Florapark, we have been serving real Turkish döner for years — freshly sliced, with crispy flatbread and homemade sauces.",
      p2: "Only the best quality matters to us: fresh vegetables, spiced meat from the spit and traditional recipes. Stop by and taste the difference.",
      badge1: "Fresh ingredients",
      badge2: "Traditional recipes",
      badge3: "Sliced from the spit",
    },
    contact: {
      title: "Contact & Opening Hours",
      addressLabel: "Address",
      addressExtra: "Next to Spargelhalle & Getränkequelle",
      phoneLabel: "Phone",
      noWhatsapp: "No WhatsApp — calls only!",
      emailLabel: "Email",
      hoursLabel: "Opening Hours",
      monSat: "Monday–Saturday",
      monSatTime: "10:00 AM–8:00 PM",
      sun: "Sunday",
      sunClosed: "Closed",
      mapLabel: "How to find us",
      directions: "Get directions",
    },
    footer: {
      hours: "Opening Hours",
      rights: "All rights reserved.",
      legal: "Legal",
      imprint: "Imprint",
      privacy: "Privacy Policy",
      cookies: "Cookie Settings",
    },
    cookie: {
      title: "We respect your privacy",
      text: "We only use technically necessary cookies (language & order). Optional cookies for the embedded Google Maps are only loaded after your consent.",
      acceptAll: "Accept all",
      necessaryOnly: "Necessary only",
    },
  },
  tr: {
    nav: { menu: "Menü", about: "Hakkımızda", contact: "İletişim", callOrder: "Ara & Sipariş Ver" },
    hero: {
      subline: "Magdeburg'un en lezzetli döneri — Florapark'ta taze kesim.",
      preorder: "Hemen ön sipariş",
      toMenu: "Menüyü Gör",
      hours: "Pzt–Cmt: 10:00–20:00",
    },
    banner: { line1: "Siparişler SADECE telefonla — WhatsApp yok!", line2: "Ara, ön sipariş ver, teslim alırken öde" },
    menu: { title: "Menü", subtitle: "Taze hazırlanır, tam Florapark'ta", add: "Ekle" },
    categories: {
      doner: "Döner Yemekleri",
      pizza: "Lahmacun",
      durum: "Dürüm",
      teller: "Tabaklar & Box",
      fastfood: "Fast Food",
      salate: "Salatalar",
      menus: "Menüler",
      getranke: "İçecekler",
    },
    cart: {
      title: "Siparişiniz",
      empty: "Henüz seçim yok.",
      emptyHint: "Eklemek için bir yemeğe dokun.",
      total: "Toplam",
      payNote: "Teslim alırken ödeme — sadece nakit",
      checkout: "Telefonla sipariş ver",
      callInstruction: "Bizi ara ve siparişini ilet!",
      callButton: "Hemen ara",
      noWhatsapp: "WhatsApp yok — sadece telefon!",
      noteLabel: "Özel istekler",
      notePlaceholder: "Örn. ekstra acı, soğansız, alerji …",
    },
    about: {
      title: "Otantik. Taze. Efsane.",
      p1: "Magdeburg'un kalbinde, Florapark'ta, yıllardır gerçek Türk dönerini servis ediyoruz — taze kesilmiş, çıtır pide ve ev yapımı soslarla.",
      p2: "Bizim için sadece en iyi kalite önemlidir: taze sebzeler, şişten baharatlı et ve geleneksel tarifler. Uğrayın ve farkı tadın.",
      badge1: "Taze malzemeler",
      badge2: "Geleneksel tarifler",
      badge3: "Şişten kesilmiş",
    },
    contact: {
      title: "İletişim & Çalışma Saatleri",
      addressLabel: "Adres",
      addressExtra: "Spargelhalle & Getränkequelle yanında",
      phoneLabel: "Telefon",
      noWhatsapp: "WhatsApp yok — sadece arama!",
      emailLabel: "E-posta",
      hoursLabel: "Çalışma Saatleri",
      monSat: "Pazartesi–Cumartesi",
      monSatTime: "10:00–20:00",
      sun: "Pazar",
      sunClosed: "Kapalı",
      mapLabel: "Bizi nasıl bulursunuz",
      directions: "Yol tarifi al",
    },
    footer: {
      hours: "Çalışma Saatleri",
      rights: "Tüm hakları saklıdır.",
      legal: "Yasal",
      imprint: "Künye",
      privacy: "Gizlilik Politikası",
      cookies: "Çerez Ayarları",
    },
    cookie: {
      title: "Gizliliğinize saygı duyuyoruz",
      text: "Yalnızca teknik olarak gerekli çerezleri kullanırız (dil & sipariş). Google Haritalar için isteğe bağlı çerezler yalnızca onayınızdan sonra yüklenir.",
      acceptAll: "Tümünü kabul et",
      necessaryOnly: "Yalnızca gerekli",
    },
  },
  ar: {
    nav: { menu: "قائمة الطعام", about: "من نحن", contact: "اتصل بنا", callOrder: "اتصل واطلب" },
    hero: {
      subline: "ألذ دونر في ماغدبورغ — مقطّع طازجاً في فلوراپارك.",
      preorder: "اطلب مسبقاً الآن",
      toMenu: "عرض القائمة",
      hours: "الإثنين–السبت: 10:00–20:00",
    },
    banner: { line1: "الطلبات عبر الهاتف فقط — لا واتساب!", line2: "اتصل، اطلب مسبقاً، وادفع عند الاستلام" },
    menu: { title: "قائمة الطعام", subtitle: "طازج ومحضّر، مباشرةً في فلوراپارك", add: "أضف" },
    categories: {
      doner: "أطباق الدونر",
      pizza: "بيتزا تركية",
      durum: "دورم",
      teller: "أطباق وعلب",
      fastfood: "وجبات سريعة",
      salate: "سلطات",
      menus: "وجبات",
      getranke: "مشروبات",
    },
    cart: {
      title: "طلبك",
      empty: "لم يتم اختيار شيء بعد.",
      emptyHint: "اضغط على طبق لإضافته.",
      total: "الإجمالي",
      payNote: "الدفع عند الاستلام — نقداً فقط",
      checkout: "اطلب عبر الهاتف",
      callInstruction: "اتصل بنا وأخبرنا بطلبك!",
      callButton: "اتصل الآن",
      noWhatsapp: "لا واتساب — مكالمات هاتفية فقط!",
      noteLabel: "ملاحظات خاصة",
      notePlaceholder: "مثال: حار جداً، بدون بصل، حساسية …",
    },
    about: {
      title: "أصيل. طازج. أسطوري.",
      p1: "في قلب ماغدبورغ، في فلوراپارك، نقدّم منذ سنوات الدونر التركي الأصيل — مقطّع طازجاً، مع خبز مقرمش وصلصات منزلية.",
      p2: "الجودة الأفضل هي كل ما يهمنا: خضار طازجة، لحم متبّل من السيخ ووصفات تقليدية. تفضّل بزيارتنا وتذوّق الفرق.",
      badge1: "مكونات طازجة",
      badge2: "وصفات تقليدية",
      badge3: "مقطّع من السيخ",
    },
    contact: {
      title: "التواصل وساعات العمل",
      addressLabel: "العنوان",
      addressExtra: "بجانب Spargelhalle و Getränkequelle",
      phoneLabel: "الهاتف",
      noWhatsapp: "لا واتساب — مكالمات فقط!",
      emailLabel: "البريد الإلكتروني",
      hoursLabel: "ساعات العمل",
      monSat: "الإثنين–السبت",
      monSatTime: "10:00–20:00",
      sun: "الأحد",
      sunClosed: "مغلق",
      mapLabel: "كيف تجدنا",
      directions: "احصل على الاتجاهات",
    },
    footer: {
      hours: "ساعات العمل",
      rights: "جميع الحقوق محفوظة.",
      legal: "قانوني",
      imprint: "بيانات النشر",
      privacy: "سياسة الخصوصية",
      cookies: "إعدادات ملفات تعريف الارتباط",
    },
    cookie: {
      title: "نحن نحترم خصوصيتك",
      text: "نستخدم فقط ملفات تعريف الارتباط الضرورية تقنياً (اللغة والطلب). يتم تحميل ملفات الخريطة الاختيارية فقط بعد موافقتك.",
      acceptAll: "قبول الكل",
      necessaryOnly: "الضرورية فقط",
    },
  },
} as const

export const SIG = {
  de: {
    kicker: "Unser Aushängeschild",
    title: "Der Antalya Döner",
    lead: "Saftiges Fleisch frisch vom Spieß, knuspriges Fladenbrot, frisches Gemüse und hausgemachte Soßen — getürmt, nicht geknausert.",
    points: ["Frisch vom Spieß geschnitten", "Knuspriges Original-Fladenbrot", "Hausgemachte Soßen", "Dazu eiskalter Ayran"],
    ayran: "Ayran inklusive",
    from: "schon ab",
    order: "Antalya Döner bestellen",
    toMenu: "Ganze Karte ansehen",
  },
  en: {
    kicker: "Our signature",
    title: "The Antalya Döner",
    lead: "Juicy meat fresh off the spit, crispy flatbread, fresh veggies and homemade sauces — piled high, never skimped.",
    points: ["Sliced fresh from the spit", "Crispy original flatbread", "Homemade sauces", "Ice-cold Ayran on the side"],
    ayran: "Ayran included",
    from: "from only",
    order: "Order this döner",
    toMenu: "See the full menu",
  },
  tr: {
    kicker: "Amiral gemimiz",
    title: "Antalya Döner",
    lead: "Şişten taze sulu et, çıtır pide, taze sebzeler ve ev yapımı soslar — bol bol, cömertçe.",
    points: ["Şişten taze kesim", "Çıtır orijinal pide", "Ev yapımı soslar", "Yanında buz gibi ayran"],
    ayran: "Ayran dahil",
    from: "şu fiyattan",
    order: "Bu döneri sipariş ver",
    toMenu: "Tüm menüyü gör",
  },
  ar: {
    kicker: "نجمنا",
    title: "دونر أنطاليا",
    lead: "لحم طازج من السيخ، خبز مقرمش، خضار طازجة وصلصات منزلية — كومة سخية بلا بخل.",
    points: ["مقطّع طازجاً من السيخ", "خبز أصلي مقرمش", "صلصات منزلية", "مع عيران مثلج"],
    ayran: "عيران مجاناً",
    from: "ابتداءً من",
    order: "اطلب هذا الدونر",
    toMenu: "عرض القائمة كاملة",
  },
} as const

export const CATS = ["doner", "pizza", "durum", "teller", "fastfood", "salate", "menus", "getranke"] as const
export type Cat = (typeof CATS)[number]

export const MENU: Record<Cat, MenuItem[]> = {
  doner: [
    { id: "d01", num: "01", name: { de: "Antalya Kebab", en: "Antalya Kebab", tr: "Antalya Kebap", ar: "كباب أنطاليا" }, desc: { de: "Im Fladenbrot, Fleisch, Salat & Soße", en: "In flatbread, meat, salad & sauce", tr: "Pidede, et, salata ve sos", ar: "في الخبز، لحم وسلطة وصلصة" }, price: 7.5 },
    { id: "d02", num: "02", name: { de: "Antalya Kebab + Käse", en: "Antalya Kebab + Cheese", tr: "Antalya Kebap + Peynir", ar: "كباب أنطاليا + جبن" }, desc: { de: "Im Fladenbrot, Fleisch, Salat, Soße & Käse", en: "In flatbread, meat, salad, sauce & cheese", tr: "Pidede, et, salata, sos ve peynir", ar: "في الخبز، لحم وسلطة وصلصة وجبن" }, price: 8.5 },
    { id: "d03", num: "03", name: { de: "Antalya Kebab Spezial", en: "Antalya Kebab Special", tr: "Antalya Kebap Özel", ar: "كباب أنطاليا خاص" }, desc: { de: "Im Fladenbrot mit extra Fleisch, Salat & Soße", en: "In flatbread with extra meat, salad & sauce", tr: "Pidede ekstra et, salata ve sos", ar: "في الخبز مع لحم إضافي وسلطة وصلصة" }, price: 8.5 },
    { id: "d04", num: "04", name: { de: "Antalya Kebab", en: "Antalya Kebab", tr: "Antalya Kebap", ar: "كباب أنطاليا" }, desc: { de: "Im Fladenbrot nur mit Fleisch & Soße", en: "In flatbread with meat & sauce only", tr: "Pidede sadece et ve sos", ar: "في الخبز مع اللحم والصلصة فقط" }, price: 8.5 },
    { id: "d05", num: "05", name: { de: "Antalya Kebab Mega", en: "Antalya Kebab Mega", tr: "Antalya Kebap Mega", ar: "كباب أنطاليا ميجا" }, desc: { de: "Extra Fleisch, Salat, Soße & Käse", en: "Extra meat, salad, sauce & cheese", tr: "Ekstra et, salata, sos ve peynir", ar: "لحم إضافي وسلطة وصلصة وجبن" }, price: 9.0 },
    { id: "d06", num: "06", name: { de: "Antalya Kebab Vegetarisch", en: "Antalya Kebab Vegetarian", tr: "Antalya Kebap Vejetaryen", ar: "كباب أنطاليا نباتي" }, desc: { de: "Im Fladenbrot mit Salat & Soße", en: "In flatbread with salad & sauce", tr: "Pidede salata ve sos", ar: "في الخبز مع سلطة وصلصة" }, price: 6.5 },
    { id: "d07", num: "07", name: { de: "Antalya Kebab Vegetarisch + Käse", en: "Antalya Kebab Vegetarian + Cheese", tr: "Antalya Kebap Vejetaryen + Peynir", ar: "كباب أنطاليا نباتي + جبن" }, desc: { de: "Mit Salat, Soße & Käse", en: "With salad, sauce & cheese", tr: "Salata, sos ve peynir", ar: "مع سلطة وصلصة وجبن" }, price: 7.0 },
    { id: "d08", num: "08", name: { de: "Falafel im Fladenbrot", en: "Falafel in Flatbread", tr: "Pidede Falafel", ar: "فلافل في الخبز" }, desc: { de: "Mit Salat & Soße", en: "With salad & sauce", tr: "Salata ve sos ile", ar: "مع سلطة وصلصة" }, price: 7.5 },
    { id: "d09", num: "09", name: { de: "Halloumi im Fladenbrot", en: "Halloumi in Flatbread", tr: "Pidede Hellim", ar: "حلوم في الخبز" }, desc: { de: "Mit Salat & Soße", en: "With salad & sauce", tr: "Salata ve sos ile", ar: "مع سلطة وصلصة" }, price: 7.5 },
  ],
  pizza: [
    { id: "p10", num: "10", name: { de: "Türkische Pizza", en: "Turkish Pizza", tr: "Lahmacun", ar: "بيتزا تركية" }, desc: { de: "Mit Fleisch, Salat & Soße", en: "With meat, salad & sauce", tr: "Et, salata ve sos ile", ar: "مع لحم وسلطة وصلصة" }, price: 8.5 },
    { id: "p11", num: "11", name: { de: "Türkische Pizza + Käse", en: "Turkish Pizza + Cheese", tr: "Lahmacun + Peynir", ar: "بيتزا تركية + جبن" }, desc: { de: "Mit Fleisch, Salat, Soße & Käse", en: "With meat, salad, sauce & cheese", tr: "Et, salata, sos ve peynir", ar: "مع لحم وسلطة وصلصة وجبن" }, price: 9.5 },
    { id: "p12", num: "12", name: { de: "Türkische Pizza Spezial", en: "Turkish Pizza Special", tr: "Lahmacun Özel", ar: "بيتزا تركية خاصة" }, desc: { de: "Mit extra Fleisch, Salat & Soße", en: "With extra meat, salad & sauce", tr: "Ekstra et, salata ve sos", ar: "مع لحم إضافي وسلطة وصلصة" }, price: 9.5 },
    { id: "p13", num: "13", name: { de: "Türkische Pizza", en: "Turkish Pizza", tr: "Lahmacun", ar: "بيتزا تركية" }, desc: { de: "Nur mit Fleisch & Soße", en: "With meat & sauce only", tr: "Sadece et ve sos", ar: "مع اللحم والصلصة فقط" }, price: 10.0 },
    { id: "p14", num: "14", name: { de: "Türkische Pizza Mega", en: "Turkish Pizza Mega", tr: "Lahmacun Mega", ar: "بيتزا تركية ميجا" }, desc: { de: "Extra Fleisch, Salat, Soße & Käse", en: "Extra meat, salad, sauce & cheese", tr: "Ekstra et, salata, sos ve peynir", ar: "لحم إضافي وسلطة وصلصة وجبن" }, price: 10.0 },
    { id: "p15", num: "15", name: { de: "Türkische Pizza Vegetarisch", en: "Turkish Pizza Vegetarian", tr: "Lahmacun Vejetaryen", ar: "بيتزا تركية نباتية" }, desc: { de: "Mit Salat & Soße", en: "With salad & sauce", tr: "Salata ve sos ile", ar: "مع سلطة وصلصة" }, price: 8.0 },
    { id: "p16", num: "16", name: { de: "Türkische Pizza Vegetarisch + Käse", en: "Turkish Pizza Vegetarian + Cheese", tr: "Lahmacun Vejetaryen + Peynir", ar: "بيتزا تركية نباتية + جبن" }, desc: { de: "Mit Salat, Soße & Käse", en: "With salad, sauce & cheese", tr: "Salata, sos ve peynir", ar: "مع سلطة وصلصة وجبن" }, price: 8.5 },
    { id: "p17", num: "17", name: { de: "Türkische Pizza Falafel", en: "Turkish Pizza Falafel", tr: "Lahmacun Falafel", ar: "بيتزا تركية فلافل" }, desc: { de: "Mit Salat & Soße", en: "With salad & sauce", tr: "Salata ve sos ile", ar: "مع سلطة وصلصة" }, price: 9.0 },
    { id: "p18", num: "18", name: { de: "Türkische Pizza Halloumi", en: "Turkish Pizza Halloumi", tr: "Lahmacun Hellim", ar: "بيتزا تركية حلوم" }, desc: { de: "Mit Salat & Soße", en: "With salad & sauce", tr: "Salata ve sos ile", ar: "مع سلطة وصلصة" }, price: 9.0 },
  ],
  durum: [
    { id: "u20", num: "20", name: { de: "Dürüm", en: "Dürüm", tr: "Dürüm", ar: "دورم" }, desc: { de: "Mit Fleisch, Salat & Soße", en: "With meat, salad & sauce", tr: "Et, salata ve sos ile", ar: "مع لحم وسلطة وصلصة" }, price: 8.0 },
    { id: "u21", num: "21", name: { de: "Dürüm + Käse", en: "Dürüm + Cheese", tr: "Dürüm + Peynir", ar: "دورم + جبن" }, desc: { de: "Mit Fleisch, Salat, Soße & Käse", en: "With meat, salad, sauce & cheese", tr: "Et, salata, sos ve peynir", ar: "مع لحم وسلطة وصلصة وجبن" }, price: 9.0 },
    { id: "u22", num: "22", name: { de: "Dürüm Spezial", en: "Dürüm Special", tr: "Dürüm Özel", ar: "دورم خاص" }, desc: { de: "Mit extra Fleisch, Salat & Soße", en: "With extra meat, salad & sauce", tr: "Ekstra et, salata ve sos", ar: "مع لحم إضافي وسلطة وصلصة" }, price: 9.0 },
    { id: "u23", num: "23", name: { de: "Dürüm", en: "Dürüm", tr: "Dürüm", ar: "دورم" }, desc: { de: "Nur Fleisch & Soße", en: "Meat & sauce only", tr: "Sadece et ve sos", ar: "مع اللحم والصلصة فقط" }, price: 9.5 },
    { id: "u24", num: "24", name: { de: "Dürüm Mega", en: "Dürüm Mega", tr: "Dürüm Mega", ar: "دورم ميجا" }, desc: { de: "Extra Fleisch, Salat, Soße & Käse", en: "Extra meat, salad, sauce & cheese", tr: "Ekstra et, salata, sos ve peynir", ar: "لحم إضافي وسلطة وصلصة وجبن" }, price: 9.5 },
    { id: "u25", num: "25", name: { de: "Dürüm Vegetarisch", en: "Dürüm Vegetarian", tr: "Dürüm Vejetaryen", ar: "دورم نباتي" }, desc: { de: "Mit Salat & Soße", en: "With salad & sauce", tr: "Salata ve sos ile", ar: "مع سلطة وصلصة" }, price: 7.5 },
    { id: "u26", num: "26", name: { de: "Dürüm Vegetarisch + Käse", en: "Dürüm Vegetarian + Cheese", tr: "Dürüm Vejetaryen + Peynir", ar: "دورم نباتي + جبن" }, desc: { de: "Mit Salat, Soße & Käse", en: "With salad, sauce & cheese", tr: "Salata, sos ve peynir", ar: "مع سلطة وصلصة وجبن" }, price: 8.0 },
    { id: "u27", num: "27", name: { de: "Dürüm Falafel", en: "Dürüm Falafel", tr: "Dürüm Falafel", ar: "دورم فلافل" }, desc: { de: "Mit Salat & Soße", en: "With salad & sauce", tr: "Salata ve sos ile", ar: "مع سلطة وصلصة" }, price: 8.5 },
    { id: "u28", num: "28", name: { de: "Dürüm Halloumi", en: "Dürüm Halloumi", tr: "Dürüm Hellim", ar: "دورم حلوم" }, desc: { de: "Mit Salat & Soße", en: "With salad & sauce", tr: "Salata ve sos ile", ar: "مع سلطة وصلصة" }, price: 9.0 },
  ],
  teller: [
    { id: "t30", num: "30", name: { de: "Antalya Kebab Teller", en: "Antalya Kebab Plate", tr: "Antalya Kebap Tabağı", ar: "صحن كباب أنطاليا" }, desc: { de: "Mit Fleisch, Salat", en: "With meat, salad", tr: "Et ve salata ile", ar: "مع لحم وسلطة" }, price: 10.0 },
    { id: "t31", num: "31", name: { de: "Antalya Kebab Teller", en: "Antalya Kebab Plate", tr: "Antalya Kebap Tabağı", ar: "صحن كباب أنطاليا" }, desc: { de: "Nur Fleisch, Soße & Pommes o. Nudeln", en: "Meat only, sauce & fries or pasta", tr: "Sadece et, sos ve patates veya makarna", ar: "لحم فقط، صلصة وبطاطس أو معكرونة" }, price: 10.5 },
    { id: "t32", num: "32", name: { de: "Antalya Kebab Teller", en: "Antalya Kebab Plate", tr: "Antalya Kebap Tabağı", ar: "صحن كباب أنطاليا" }, desc: { de: "Fleisch, Salat, Soße & Pommes o. Nudeln", en: "Meat, salad, sauce & fries or pasta", tr: "Et, salata, sos ve patates veya makarna", ar: "لحم وسلطة وصلصة وبطاطس أو معكرونة" }, price: 11.0 },
    { id: "t33", num: "33", name: { de: "Antalya Kebab Mega Teller", en: "Antalya Kebab Mega Plate", tr: "Antalya Kebap Mega Tabağı", ar: "صحن كباب أنطاليا ميجا" }, desc: { de: "Fleisch, Salat, Soße, Käse & Pommes o. Nudeln", en: "Meat, salad, sauce, cheese & fries or pasta", tr: "Et, salata, sos, peynir ve patates veya makarna", ar: "لحم وسلطة وصلصة وجبن وبطاطس أو معكرونة" }, price: 12.0 },
    { id: "t34", num: "34", name: { de: "Antalya Kebab Box", en: "Antalya Kebab Box", tr: "Antalya Kebap Box", ar: "علبة كباب أنطاليا" }, desc: { de: "Mit Fleisch, Salat & Soße", en: "With meat, salad & sauce", tr: "Et, salata ve sos ile", ar: "مع لحم وسلطة وصلصة" }, price: 8.0 },
    { id: "t35", num: "35", name: { de: "Antalya Kebab Box", en: "Antalya Kebab Box", tr: "Antalya Kebap Box", ar: "علبة كباب أنطاليا" }, desc: { de: "Mit Fleisch, Soße & Pommes o. Nudeln", en: "With meat, sauce & fries or pasta", tr: "Et, sos ve patates veya makarna ile", ar: "مع لحم وصلصة وبطاطس أو معكرونة" }, price: 8.0 },
    { id: "t36", num: "36", name: { de: "Antalya Kebab Box", en: "Antalya Kebab Box", tr: "Antalya Kebap Box", ar: "علبة كباب أنطاليا" }, desc: { de: "Nur Fleisch & Soße", en: "Meat & sauce only", tr: "Sadece et ve sos", ar: "مع اللحم والصلصة فقط" }, price: 9.0 },
    { id: "t37", num: "37", name: { de: "Kiddy Box", en: "Kiddy Box", tr: "Çocuk Box", ar: "علبة الأطفال" }, desc: { de: "Mit Fleisch o. 3 Nuggets, Pommes", en: "With meat or 3 nuggets, fries", tr: "Et veya 3 nugget, patates ile", ar: "مع لحم أو 3 ناغتس وبطاطس" }, price: 8.0 },
    { id: "t38", num: "38", name: { de: "Halloumi Teller", en: "Halloumi Plate", tr: "Hellim Tabağı", ar: "صحن حلوم" }, desc: { de: "Mit Pommes o. Nudelsalat", en: "With fries or pasta salad", tr: "Patates veya makarna salatası ile", ar: "مع بطاطس أو سلطة معكرونة" }, price: 11.0 },
    { id: "t39", num: "39", name: { de: "Falafel Teller", en: "Falafel Plate", tr: "Falafel Tabağı", ar: "صحن فلافل" }, desc: { de: "Mit Pommes o. Nudelsalat", en: "With fries or pasta salad", tr: "Patates veya makarna salatası ile", ar: "مع بطاطس أو سلطة معكرونة" }, price: 11.0 },
  ],
  fastfood: [
    { id: "f40", num: "40", name: { de: "Pommes frites", en: "French Fries", tr: "Patates Kızartması", ar: "بطاطس مقلية" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 5.0 },
    { id: "f41", num: "41", name: { de: "Kroketten", en: "Croquettes", tr: "Kroket", ar: "كروكيت" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 5.0 },
    { id: "f42", num: "42", name: { de: "Hamburger", en: "Hamburger", tr: "Hamburger", ar: "همبرغر" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 5.0 },
    { id: "f43", num: "43", name: { de: "Cheeseburger", en: "Cheeseburger", tr: "Çizburger", ar: "تشيز برغر" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 5.5 },
    { id: "f44", num: "44", name: { de: "Crispy Chicken Burger", en: "Crispy Chicken Burger", tr: "Çıtır Tavuk Burger", ar: "برغر دجاج مقرمش" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 5.0 },
    { id: "f45", num: "45", name: { de: "Chicken-Nuggets (6er)", en: "Chicken Nuggets (6 pcs)", tr: "Tavuk Nugget (6 adet)", ar: "ناغتس دجاج (6 قطع)" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 5.5 },
    { id: "f46", num: "46", name: { de: "Chicken-Wings (6er)", en: "Chicken Wings (6 pcs)", tr: "Tavuk Kanat (6 adet)", ar: "أجنحة دجاج (6 قطع)" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 5.5 },
    { id: "f47", num: "47", name: { de: "Currywurst mit Brot", en: "Currywurst with Bread", tr: "Ekmekli Currywurst", ar: "نقانق كاري مع خبز" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 5.0 },
  ],
  salate: [
    { id: "s50", num: "50", name: { de: "Gemischter Salat", en: "Mixed Salad", tr: "Karışık Salata", ar: "سلطة مشكلة" }, desc: { de: "Mit Salaten nach Wahl", en: "With salads of your choice", tr: "Seçtiğiniz salatalarla", ar: "مع السلطات حسب الاختيار" }, price: 6.5 },
    { id: "s51", num: "51", name: { de: "Gemischter Salat Käse", en: "Mixed Salad with Cheese", tr: "Peynirli Karışık Salata", ar: "سلطة مشكلة بالجبن" }, desc: { de: "Mit Salaten nach Wahl & Käse", en: "With salads of your choice & cheese", tr: "Seçtiğiniz salatalar ve peynir ile", ar: "مع السلطات حسب الاختيار وجبن" }, price: 7.0 },
    { id: "s52", num: "52", name: { de: "Gemischter Salat Kebab", en: "Mixed Salad with Kebab", tr: "Kebaplı Karışık Salata", ar: "سلطة مشكلة بالكباب" }, desc: { de: "Mit Salaten nach Wahl & Kebab-Fleisch", en: "With salads & kebab meat", tr: "Salatalar ve kebap eti ile", ar: "مع السلطات ولحم الكباب" }, price: 8.0 },
    { id: "s53", num: "53", name: { de: "Gemischter Salat Kebab Käse", en: "Mixed Salad Kebab & Cheese", tr: "Kebaplı Peynirli Salata", ar: "سلطة مشكلة بالكباب والجبن" }, desc: { de: "Salate, Kebab-Fleisch & Käse", en: "Salads, kebab meat & cheese", tr: "Salatalar, kebap eti ve peynir", ar: "السلطات ولحم الكباب والجبن" }, price: 8.5 },
    { id: "s54", num: "54", name: { de: "Tonno Salat", en: "Tuna Salad", tr: "Ton Balıklı Salata", ar: "سلطة تونة" }, desc: { de: "Tomaten, Eisberg, Gurken, Zwiebeln & Thunfisch", en: "Tomatoes, iceberg, cucumber, onions & tuna", tr: "Domates, marul, salatalık, soğan ve ton balığı", ar: "طماطم وخس وخيار وبصل وتونة" }, price: 8.0 },
  ],
  menus: [
    { id: "m60", num: "60", name: { de: "Hamburger Menü", en: "Hamburger Combo", tr: "Hamburger Menü", ar: "وجبة همبرغر" }, desc: { de: "Mit Salat, Soße & Pommes oder Nudeln", en: "With salad, sauce & fries or pasta", tr: "Salata, sos ve patates veya makarna ile", ar: "مع سلطة وصلصة وبطاطس أو معكرونة" }, price: 9.5 },
    { id: "m61", num: "61", name: { de: "Cheeseburger Menü", en: "Cheeseburger Combo", tr: "Çizburger Menü", ar: "وجبة تشيز برغر" }, desc: { de: "Mit Salat, Soße & Pommes oder Nudeln", en: "With salad, sauce & fries or pasta", tr: "Salata, sos ve patates veya makarna ile", ar: "مع سلطة وصلصة وبطاطس أو معكرونة" }, price: 10.0 },
    { id: "m62", num: "62", name: { de: "Crispy-Chicken-Burger Menü", en: "Crispy Chicken Burger Combo", tr: "Çıtır Tavuk Burger Menü", ar: "وجبة برغر دجاج مقرمش" }, desc: { de: "Mit Salat, Soße & Pommes oder Nudeln", en: "With salad, sauce & fries or pasta", tr: "Salata, sos ve patates veya makarna ile", ar: "مع سلطة وصلصة وبطاطس أو معكرونة" }, price: 9.5 },
    { id: "m63", num: "63", name: { de: "Chicken-Nuggets Menü", en: "Chicken Nuggets Combo", tr: "Tavuk Nugget Menü", ar: "وجبة ناغتس دجاج" }, desc: { de: "Mit Salat, Soße & Pommes oder Nudeln", en: "With salad, sauce & fries or pasta", tr: "Salata, sos ve patates veya makarna ile", ar: "مع سلطة وصلصة وبطاطس أو معكرونة" }, price: 9.5 },
    { id: "m64", num: "64", name: { de: "Currywurst Menü", en: "Currywurst Combo", tr: "Currywurst Menü", ar: "وجبة نقانق كاري" }, desc: { de: "Mit Salat, Soße & Pommes oder Nudeln", en: "With salad, sauce & fries or pasta", tr: "Salata, sos ve patates veya makarna ile", ar: "مع سلطة وصلصة وبطاطس أو معكرونة" }, price: 9.5 },
    { id: "m65", num: "65", name: { de: "Hähnchenschnitzel Menü", en: "Chicken Schnitzel Combo", tr: "Tavuk Şnitzel Menü", ar: "وجبة شنيتزل دجاج" }, desc: { de: "Mit Salat, Soße & Pommes oder Nudeln", en: "With salad, sauce & fries or pasta", tr: "Salata, sos ve patates veya makarna ile", ar: "مع سلطة وصلصة وبطاطس أو معكرونة" }, price: 9.5 },
  ],
  getranke: [
    { id: "g01", num: "", name: { de: "Kaffee / Cappuccino", en: "Coffee / Cappuccino", tr: "Kahve / Cappuccino", ar: "قهوة / كابتشينو" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 1.5 },
    { id: "g02", num: "", name: { de: "Tasse Tee", en: "Cup of Tea", tr: "Fincan Çay", ar: "فنجان شاي" }, desc: { de: "Verschiedene Sorten", en: "Various varieties", tr: "Çeşitli türler", ar: "أنواع مختلفة" }, price: 1.5 },
    { id: "g03", num: "", name: { de: "Cola / Fanta / Sprite 0,5l", en: "Coke / Fanta / Sprite 0.5l", tr: "Cola / Fanta / Sprite 0,5l", ar: "كولا / فانتا / سبرايت 0.5 لتر" }, desc: { de: "+0,25 € Pfand", en: "+€0.25 deposit", tr: "+0,25 € depozito", ar: "+0.25 يورو تأمين" }, price: 2.5 },
    { id: "g04", num: "", name: { de: "Cola light / Mezzo Mix 0,5l", en: "Diet Coke / Mezzo Mix 0.5l", tr: "Cola light / Mezzo Mix 0,5l", ar: "كولا دايت / ميزو ميكس 0.5 لتر" }, desc: { de: "+0,25 € Pfand", en: "+€0.25 deposit", tr: "+0,25 € depozito", ar: "+0.25 يورو تأمين" }, price: 2.5 },
    { id: "g05", num: "", name: { de: "Eistee / Apfelschorle 0,5l", en: "Iced Tea / Apple Spritzer 0.5l", tr: "Buzlu Çay / Elma Sodası 0,5l", ar: "شاي مثلج / عصير تفاح 0.5 لتر" }, desc: { de: "+0,25 € Pfand", en: "+€0.25 deposit", tr: "+0,25 € depozito", ar: "+0.25 يورو تأمين" }, price: 2.5 },
    { id: "g06", num: "", name: { de: "Wasser (still) 0,5l", en: "Water (still) 0.5l", tr: "Su (gazsız) 0,5l", ar: "ماء (بدون غاز) 0.5 لتر" }, desc: { de: "+0,25 € Pfand", en: "+€0.25 deposit", tr: "+0,25 € depozito", ar: "+0.25 يورو تأمين" }, price: 2.0 },
    { id: "g07", num: "", name: { de: "Uludag 0,33l", en: "Uludag 0.33l", tr: "Uludağ 0,33l", ar: "أولوداغ 0.33 لتر" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 2.0 },
    { id: "g08", num: "", name: { de: "Fanta Exotic 0,33l", en: "Fanta Exotic 0.33l", tr: "Fanta Exotic 0,33l", ar: "فانتا إكزوتيك 0.33 لتر" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 2.0 },
    { id: "g09", num: "", name: { de: "Ayran 0,25l", en: "Ayran 0.25l", tr: "Ayran 0,25l", ar: "عيران 0.25 لتر" }, desc: { de: "", en: "", tr: "", ar: "" }, price: 2.0 },
  ],
}

export const ALLERGENS: Record<string, string[]> = {
  d01: ["A", "G", "J", "K"], d02: ["A", "G", "J", "K"], d03: ["A", "G", "J", "K"],
  d04: ["A", "G", "J", "K"], d05: ["A", "G", "J", "K"], d06: ["A", "G", "J", "K"],
  d07: ["A", "G", "J", "K"], d08: ["A", "F", "G", "J", "K"], d09: ["A", "G", "J", "K"],
  p10: ["A", "G", "J", "K"], p11: ["A", "G", "J", "K"], p12: ["A", "G", "J", "K"],
  p13: ["A", "G", "J", "K"], p14: ["A", "G", "J", "K"], p15: ["A", "G", "J", "K"],
  p16: ["A", "G", "J", "K"], p17: ["A", "F", "G", "J", "K"], p18: ["A", "G", "J", "K"],
  u20: ["A", "G", "J", "K"], u21: ["A", "G", "J", "K"], u22: ["A", "G", "J", "K"],
  u23: ["A", "G", "J", "K"], u24: ["A", "G", "J", "K"], u25: ["A", "G", "J", "K"],
  u26: ["A", "G", "J", "K"], u27: ["A", "F", "G", "J", "K"], u28: ["A", "G", "J", "K"], u29: ["A", "G", "J", "K"],
  t30: ["A", "G", "J"], t31: ["A", "G", "J"], t32: ["A", "G", "J"], t33: ["A", "G", "J"],
  t34: ["A", "G", "J"], t35: ["A", "G", "J"], t36: ["A", "G", "J"], t37: ["A", "G", "J"],
  t38: ["A", "G", "J"], t39: ["A", "G", "J"],
  f40: ["A"], f41: ["A", "C", "G"], f42: ["A", "C", "G", "J"],
  f43: ["A", "C", "G", "J"], f44: ["A", "C", "G", "J"], f45: ["A", "C", "G"],
  f46: ["A", "G", "J"], f47: ["A", "G", "J"],
  s50: ["G", "J", "K"], s51: ["G", "J", "K"], s52: ["A", "G", "J", "K"],
  s53: ["A", "G", "J", "K"], s54: ["D", "G", "J"],
  m60: ["A", "C", "G", "J"], m61: ["A", "C", "G", "J"], m62: ["A", "C", "G", "J"],
  m63: ["A", "C", "G"], m64: ["A", "G", "J"], m65: ["A", "C", "G"],
  g01: ["G"], g09: ["G"],
}

export const ALLERGEN_LEGEND: { key: string; label: string }[] = [
  { key: "A", label: "Glutenhaltiges Getreide" },
  { key: "B", label: "Krebstiere" },
  { key: "C", label: "Eier" },
  { key: "D", label: "Fisch" },
  { key: "E", label: "Erdnüsse" },
  { key: "F", label: "Sojabohnen" },
  { key: "G", label: "Milch / Laktose" },
  { key: "H", label: "Schalenfrüchte" },
  { key: "I", label: "Sellerie" },
  { key: "J", label: "Senf" },
  { key: "K", label: "Sesam" },
  { key: "M", label: "Lupinen" },
  { key: "N", label: "Weichtiere" },
]

export const fmt = (v: number) => v.toFixed(2).replace(".", ",") + " €"

export const FLAGS: Record<Lang, string> = {
  de: '<svg viewBox="0 0 60 40" preserveAspectRatio="xMidYMid slice"><rect width="60" height="13.34" fill="#000"/><rect y="13.34" width="60" height="13.33" fill="#dd0000"/><rect y="26.67" width="60" height="13.33" fill="#ffce00"/></svg>',
  en: '<svg viewBox="0 0 60 40" preserveAspectRatio="xMidYMid slice"><clipPath id="pgUk"><rect width="60" height="40"/></clipPath><g clip-path="url(#pgUk)"><rect width="60" height="40" fill="#012169"/><path d="M0,0 L60,40 M60,0 L0,40" stroke="#fff" stroke-width="8"/><path d="M0,0 L60,40" stroke="#c8102e" stroke-width="4"/><path d="M60,0 L0,40" stroke="#c8102e" stroke-width="4"/><path d="M30,0 V40 M0,20 H60" stroke="#fff" stroke-width="12"/><path d="M30,0 V40 M0,20 H60" stroke="#c8102e" stroke-width="7"/></g></svg>',
  tr: '<svg viewBox="0 0 60 40" preserveAspectRatio="xMidYMid slice"><rect width="60" height="40" fill="#e30a17"/><circle cx="25" cy="20" r="9" fill="#fff"/><circle cx="28" cy="20" r="7" fill="#e30a17"/><path d="M39,14.5 l1.6,3.4 3.7,0.3 -2.8,2.4 0.9,3.6 -3.4,-2 -3.4,2 0.9,-3.6 -2.8,-2.4 3.7,-0.3 z" fill="#fff"/></svg>',
  ar: '<svg viewBox="0 0 60 40" preserveAspectRatio="xMidYMid slice"><rect width="60" height="40" fill="#fff"/><rect x="15" width="45" height="13.34" fill="#00732f"/><rect x="15" y="26.67" width="45" height="13.33" fill="#000"/><rect width="15" height="40" fill="#ff0000"/></svg>',
}

export const LANG_LIST: { code: Lang; label: string }[] = [
  { code: "de", label: "DE" },
  { code: "en", label: "EN" },
  { code: "tr", label: "TR" },
  { code: "ar", label: "AR" },
]

export const MARQUEE_WORDS = ["DÖNER", "DÜRÜM", "LAHMACUN", "FALAFEL", "HALLOUMI", "KEBAB", "AYRAN"]
